### ISSUE TITLE
Support passing tags to S3 bucket

### ISSUE THREAD

**Issue by afiune** [lacework/terraform-aws-cloudtrail#5]
Customers might want to pass tags to the S3 bucket we create,
we should add an input to allow them to do that.

**Comment by BillWeiss-at** [comment]
I'm fairly sure I'm the customer that caused this to get filed, so I thought I'd add some color :)

We have a local standard that says we set certain tags (ownership, data levels, etc) on all S3 buckets. To do that with the current code meant we copy/pasted the majority of this module into our own just to set those tags, which is a bummer.
