### ISSUE TITLE
feat: Use existing S3 bucket for access logging

### ISSUE THREAD

**Issue by loganjohnson-wk** [lacework/terraform-aws-cloudtrail#56]
# Feature Request

**I am already making a change for this. The PR will be up shortly**

## Description
We use one central bucket for access logging on S3 which we would like to incorporate into Lacework. Unfortunately to do this currently would mean creating our own cloudtrail and bucket which can then tie into the existing access log bucket. As an alternative it seems pretty simple to add an option to use an existing logging bucket and control the logging prefix. 

## Solution
Adding a `use_existing_access_log_bucket` flag which will prevent the default access logs bucket from being created.
Adding a `access_log_prefix` to control logging prefix in said log bucket.

Default logging bucket should only be created if `use_existing_cloudtrail` and `use_existing_access_log_bucket` are both false and if `bucket_enable_logs` is set to true.

To control the selection of the existing log bucket the already created `log_bucket_name` variable will be used. The `access_log_prefix` will be defaulted to "logs/" but can be changed.

**Comment by afiune** [comment]
Nicely done @loganjohnson-wk - Closing since you already did this work at https://github.com/lacework/terraform-aws-cloudtrail/pull/57

![tenor-47629575](https://user-images.githubusercontent.com/5712253/142909866-dcebca3a-e13d-4554-b29d-1a446bf434ad.gif)
