### ISSUE TITLE
feat: Creating a trail for an organization

### ISSUE THREAD

**Issue by anouarchattouna** [lacework/terraform-aws-cloudtrail#80]
# Feature Request

Adding the possibility to [create a trail for an organization](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/creating-trail-organization.html):

+ adding the [is_organization_trail](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail#is_organization_trail) argument to the `resource "aws_cloudtrail" "lacework_cloudtrail"`

**Comment by afiune** [comment]
Hy @anouarchattouna - This is a nice feature request, we will get to work on it on the next sprints.

- https://lacework.atlassian.net/browse/ALLY-941
